<?php

/**
 * @file
 * The define project entities.
 */

/**
 * Implements hook_entity_info().
 *
 * @return
 *   Array of entity info arrays.
 */
function taxi_items_entity_info() {
	
	// Init
	$entities = array();

	// Home Page
	$entities['home_page'] = array(
		'label' => t('Home Page'),
		'controller class' => 'cirroCoreController',
		'base table' => 'taxi_home_page',
		'dashboard' => array('primary'),
		'multi_img' => array(
			'slider' => array(
				'label' => 'Slider Images',
				'limit' => 5,
			),
		),
	);

	// Company Item
	$entities['company_item'] = array(
		'label' => t('Company Item'),
		'controller class' => 'cirroCoreController',
		'base table' => 'taxi_company_item',
		'dashboard' => array('add', 'table'),
	);

	/**
	 * Default entity options.
	 *
	 * This array will be added to each entity array.
	 */
	$defaults = array(
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
	);
	
	// Loop through entities
	foreach ( $entities as $index => $entity ) {
		
		// Merge defaults array
		$entities[$index] = array_merge($defaults, $entity);
		
	}
	
	return $entities;

}