<?php

// Init
$social = '';

// Build list of links with the l funcrtion

// Output nav markup
$social = "
    <div class=\"social-btn\">
      <a href=\"http://www.facebook.com/taxicommunity\" class=\"social\" data-icon=\"&#62220;\">
      </a>
     </div>
     <div class=\"social-btn\">
      <a href=\"http://twitter.com/taxicommunity\" class=\"social\" data-icon=\"&#62217;\">
      </a>
     </div>
     <div class=\"social-btn\">
      <a href=\"http://instagram.com/taxicommunity\"class=\"social\" data-icon=\"&#62253;\">
      </a>
    </div>
  ";

print $social;